### ISSUE TITLE
Glitch Image has no output

### ISSUE THREAD

**Issue by jimbobhunter** [smokris/vuo-nodes#1]
The make.glitch.image node and example is just a black output for me on MBP with NVIDIA GeForce GT 750M 2 GB

**Comment by smokris** [comment]
In macOS 10.12, [Apple changed the OpenGL driver behavior](https://www.mail-archive.com/mac-opengl@lists.apple.com/msg00094.html) such that that glitch technique no longer works.  It should still work on Mac OS 10.11 and earlier.  I'm not aware of a workaround.  I added a note to README.md (520aa53).

**Comment by jimbobhunter** [comment]
Thanks Steve,
Gotta say it's one of the more ridiculous software issues to report, that it can't glitch, lol.




Sent from my Samsung Galaxy smartphone.


-------- Original message --------
